apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fine-tune-llm
  name: fine-tune-llm
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fine-tune-llm
  type: ClusterIP
status:
  loadBalancer: {}
