apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fine-tune-llm
  name: fine-tune-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fine-tune-llm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fine-tune-llm
    spec:
      containers:
      - image: us-east4-docker.pkg.dev/fb-registry/fb-publicrepo/mandarin-ocr-app:0.02
        name: mandarin-ocr-app
        resources: {}
status: {}
